version: '3'
services:
  # Serviço Prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring

  # Serviço Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    logging:
      driver: "gelf"
      options:
        gelf-address: tcp://lab-vm1:12201
        tag: grafana
    networks:
      - monitoring
    depends_on:
      - graylog

  # Serviço Graylog
  graylog:
    deploy:
      replicas: 1
    image: graylog/graylog:4.2

    entrypoint: "/docker-entrypoint.sh"
    environment:
      GRAYLOG_PASSWORD_SECRET: "password_secret_1234"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9001/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongo:27017/graylog"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9001"
    ports:
      - "9001:9001"         # Graylog web interface and REST API
      - "1515:1514"         # Syslog TCP
      - "1515:1514/udp"     # Syslog UDP
      - "12201:12201"       # GELF TCP
      - "12201:12201/udp"   # GELF UDP
    volumes:
      - graylog_data:/usr/share/graylog/data
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - monitoring

  # MongoDB (Dependência do Graylog)
  mongo:
    deploy:
      replicas: 1
    image: "mongo:4.4"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - monitoring

  # Elasticsearch (Dependência do Graylog)
  elasticsearch:
    deploy:
      replicas: 1
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - monitoring


  # Serviço Sidecar Graylog
  sidecar:
    image: markusgulden/graylog2-sidecar-docker:latest
    environment:
        -  GS_SERVER_URL=http://graylog:9001/api/
        -  GS_NODE_ID=a-unique-id
        -  GS_SERVER_API_TOKEN=q0r5r20201kirvpdlvcq5m3hr474a39b31t0qouf6rapf4k4ble
        -  GS_LIST_LOG_FILES=/var/log/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
    networks:
      - monitoring

  # Serviço Docker Container Exporter
  docker_container_exporter:
    image: prom/container-exporter
    deploy:
      mode: global
    ports:
      - "9104:9104"
    volumes:
      - /sys/fs/cgroup:/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring
    logging:
      driver: "gelf"
      options:
        gelf-address: tcp://lab-vm1:12201
        tag: docker_container_exporter

  # Serviço CAdvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    deploy:
      mode: global 
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    logging:
      driver: "gelf"
      options:
        gelf-address: tcp://lab-vm1:12201
        tag: cadvisor

  # Serviço Node Exporter
  node_exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    ports:
      - "9100:9100"
    networks:
      - monitoring

  # MySQL (Dependência do Zabbix)
  mysql-server:
    image: mysql:8.0
    command: ["--character-set-server=utf8", "--collation-server=utf8_bin", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    ports:
      - "3306:3306"
    networks:
      - monitoring
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: tcp://lab-vm1:12201
        tag: mysql_server

  # Zabbix
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    networks:
      - monitoring
    ports:
      - "10051:10051"
    depends_on:
      - mysql-server
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: tcp://lab-vm1:12201
        tag: zabbix_server_mysql

  # Nginx (Dependência do Zabbix)
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    environment:
      ZBX_SERVER_HOST: "zabbix-server-mysql"
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    networks:
      - monitoring
    ports:
      - "80:8080"
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: tcp://lab-vm1:12201
        tag: zabbix_web

  # Serviço Zabbix Agent (Envia logs para o Zabbix)
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    environment:
      ZBX_SERVER_HOST: "zabbix-server-mysql"
    restart: always
    networks:
      - monitoring
    logging:
      driver: "gelf"
      options:
        gelf-address: tcp://lab-vm1:12201
        tag: zabbix_agent

networks:
  monitoring:
volumes:
  elasticsearch_data:
  splunk_data:
  mongo_data:
  graylog_data:
