apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  namespace: fast
  labels:
    app: hello-world-nginx
    tier: nginx
spec:
  # modifique o número de replicas de acordo com o seu caso
  replicas: 3
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80

