apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  namespace: fast # por padrao ficaria no ns default
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
    - name: hello
      image: busybox:1.28
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
